project:
  type: book

book:
  title: "SoSe 26 Computer Graphics Solutions"
  author: "Igor Dimitrov"
  date: "4/21/2026"
  chapters:
    - index.qmd
    - 01.qmd
    - 02.qmd
    # - intro.qmd
    # - summary.qmd
    # - references.qmd
    - exam/2021.qmd
  downloads: pdf

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt




